### ISSUE TITLE
Kierrätystilasto mvp (Riippuvuudet: #99)

### ISSUE THREAD

**Issue by juhakaup** [ohtuprojekti-Kierratysavustin/Kierratysavustin#104]
# Käyttäjätarina
*Käyttäjänä*
*Haluan nähdä kierrättämieni tuotteiden määrät*

### Toiminnalliset

- [x] *Jos käyttäjä on kirjautuneena*
      *Kun olen tuotelistaus näkymässä*
      *Niin käyttäjälle näytetään lisäys nappi ja lukumäärä jokaisen tuotteen kohdalla*

- [x] *Jos käyttäjä on kirjautuneena*
      *Kun olen tuotelistaus näkymässä*
      *Niin käyttäjälle näytetään poista nappi*

- [x] *Jos käyttäjä on kirjautuneena*
      *Kun olen tuotteen näkymässä*
      *Niin käyttäjälle näytetään lisäys nappi ja lukumäärä*

- [x] *Jos käyttäjä on kirjautuneena*
      *Kun käyttäjä painaa lisäys-nappia*
      *Niin tuotteen kohdalla oleva lukumäärä kasvaa yhdellä*

- [x] *Jos käyttäjä on kirjautuneena*
      *Kun olen tuotteen näkymässä*
      *Niin käyttäjälle näytetään poista nappi ja lukumäärä*

- [x] *Jos käyttäjä on kirjautuneena*
      *Kun käyttäjä painaa poista-nappia*
      *Niin tuotteen kohdalla oleva lukumäärä vähenee yhdellä*

### Ei-toiminnalliset

- [x] *Järkevä tietokanta*
- [x] *Salamannopea suorituskyky*
- [x] Käyttäjä näkee vain oman kierrätystilastonsa
- [x] [ *Datan käyttö* ]
- [ ] [ *Dokumentaation päivittäminen* ]

## Riippuvuudet
**Toteutettavissa jälkeen:** [ *Issue* ]
**Toteutettava ennen:** [ *Issue* ]
**Liittyy:** [ *#99* ]
**Vaihtoehtoinen ratkaisu:** [ *Issue* ]

## Valmis kun:
- [x] Ominaisuus on toteutettuna hyväksymiskriteerien mukaisesti ja toimii 
- [x] Ominaisuus on testattu käyttäjätarinan hyväksymiskriteerien mukaisesti ja testit menevät läpi
- [x] Kaikki ominaisuuteen liittyvä dokumentaatio on kirjoitettu
- [x] Koodi noudattaa määriteltyä koodaustyyliä
- [x] Koodi on katselmoitua: katselmoinnin on tehnyt vähintään 2 muuta henkilöä, kuin ominaisuuden koodannut henkilö
- [x] Ominaisuus mergetty mainiin ja toiminnassa staging-ympäristössä
- [x] Ominaisuus on toiminnassa tuotanto-ympäristössä

**Comment by LauriTahvanainen** [comment]
Saatiin valmiiksi tuotteen kierrätystilastointi. Jatketaan #113 .
