### ISSUE TITLE
Sivun päivittäminen selaimessa sekoittaa frontin

### ISSUE THREAD

**Issue by nikomn** [ohtuprojekti-Kierratysavustin/Kierratysavustin#71]
Koska tästä oli puhetta vain yhden jo suljetun pullarin yhteydessä, niin teen tästä tällaisen issuen, niin asia näkyy jossain.

Frontissa nappien "aktiivisuus" menee sekaisin, jos päivittää itse selaimessa sivun. Ongelma koskee ainakin tuotesivua ja siinä ainakin "Lisää suosikkeihin"/"Poista suosikeista" ja "Like/Dislike"/"Poista Like/Poista Dislike" painikkeita ja score laskuria. Lisäksi tällä on vaikutusta myös Suosikkituote listaan. Kyseessä ei ole erityisen vakava ongelma, koska näkymä korjaantuu oikeaksi jos sivun päivittää uudelleen selaimessa, mutta tällä tavalla frontin voi saada aika sekavaan tilaan.

**Steps to reproduce**

1. Avaa jonkin tuotteen sivu
2. Klikkaa "Lisää suosikkeihin" nappia -> Nappi muuttuu "Poista suosikeista"
3. Päivitä sivu (F5 tms.) -> Nappi muuttuu takaisin "Lisää suosikkeihin"

Tämän jälkeen jos klikkaa uudelleen "Lisää suosikkeihin" nappia näkyy konsolissa virheilmoitus, 
joka johtuu siitä, että back end ei hyväksy tuplien lisäämistä suosikkeihin. Kuitenkin frontissa jos menee uudelleeen klikkaamisen jälkeen etusivulle, näkyy sama tuote kahteen kertaan suosikeissa. Tilanne korjaantuu ja ylimääräinen suosikkituote tuplakirjaus poistuu, jos sivun päivittää vielä kertaalleen.

![bugi-kuva1](https://user-images.githubusercontent.com/54856295/115529977-08baf480-a29c-11eb-96b2-3a2743e0c727.png)

Sama koskee ohjeiden nappeja:

1. Avaa jonkin tuotteen sivu, jolla on ohjeita.
2. Klikkaa jonkin ohjeen Like tai Dislike painiketta -> Nappi muuttuu "Poista Like"/"Poista Dislike", äänten määrä/score vaihtuu
3. Päivitä sivu (F5 tms.) -> Nappi muuttuu takaisin "Like"/"Dislike", äänten määrä/score pysyy oikeana.

Jos tässä vaiheessa klikkaa uudelleen samaa Like/Dislike mitä aikaisemmin tulee konsoliin virheilmoitus ja nappi muuttuu takaisin "Poista Like"/"Poista Dislike"

Tällä tekniikalla on mahdollista saada frontti sekaisin, esim. frontissa saa annettu yhdelle tuotteelle kaksi dislikeä seuraavasti:

1. Klikkaa Dislike
2. Päivitä sivu
3. Klikkaa Dislike uudelleen
4. Mene pois tuotteen tiedoista esim. tuotteet listaukseen ja avaa tuotteen tiedot uudelleen.

![bugi-kuva2](https://user-images.githubusercontent.com/54856295/115530366-60596000-a29c-11eb-89ac-77df6c6b8e2e.png)
![bugi-kuva3](https://user-images.githubusercontent.com/54856295/115530046-17091080-a29c-11eb-92c1-add5bfa1be35.png)

Testasin nämä kaikki Chromella stagin serverillä pyörivässä versiossa.

**Comment by nikomn** [comment]
Siis lyhyenä summauksena näyttäisi, että jos käyttäjä päivittää itse sivun selaimessa, menee frontti epävakaaseen tilaan, josta se palautuu vasta siinä vaiheessa, jos käyttäjä päivittää sivun uudelleen selaimessa.

**Comment by nikomn** [comment]
Korjaus pullarissa #77

**Comment by nicholsss** [comment]
Mergesin pullarin, suljen tämän!
